### PR TITLE
updated react-native-vector-icons

### PR DESCRIPTION
**Pull request by cbartondock**
Wasn't sure if this even merited a pull request but what the heck. 

Thanks for the great module!

### CODE REVIEW

**Comment by vonovak** [comment]
hi, thanks for bringing this up! Actually, in this case, vector icons should've been listed in `peerDependencies`. Can you change `dependencies` to `peerDependencies`? thanks :)

**Comment by cbartondock** [comment]
Done! I switched the react-native-vector-icons version back to 3.0.0

**Comment by vonovak** [comment]
sorry, I wasn't clear enough, please keep v4 and peerDependencies. :D

**Comment by cbartondock** [comment]
Done!

**Comment by vonovak** [comment]
thanks!

**Pull request merged**
